#!/bin/sh

# This program is used to keep docker volume containers "up". While grabbing
# foreground to keep the container alive, the following command also "seems" to
# use 0 CPU in the process.

echo "Container will now idle."

shutdown() {
    echo "Container shutdown on $(date)"
    kill -SIGTERM $(pidof tail)
    exit
}

idle() {
    /usr/bin/tail -f /dev/null
}

trap "shutdown" HUP INT QUIT KILL TERM

idle & wait
